### ISSUE TITLE
fizzbuzz with if, for

### ISSUE THREAD

**Issue by DoHoon2** [DoHoon2/pizzbuzz#1]
## Tasks

- [ ] For statement(range:1 to 15)
- [ ] Print 'fizz' if i is times of 3
- [ ] Print 'fizz' if i is times of 5
- [ ] Print 'fizz' if i is times of 15
